// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizApi.Data.DatabaseContext;

#nullable disable

namespace QuizApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230606164851_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuizApi.Data.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("answerType")
                        .HasColumnType("integer");

                    b.Property<int>("correctAnswer")
                        .HasColumnType("integer");

                    b.Property<string>("question")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuizApi.Helpers.Dtos.AnswerOptionsDto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("optionA")
                        .HasColumnType("text");

                    b.Property<string>("optionB")
                        .HasColumnType("text");

                    b.Property<string>("optionC")
                        .HasColumnType("text");

                    b.Property<string>("optionD")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptionsDto");
                });

            modelBuilder.Entity("QuizApi.Helpers.Dtos.AnswerOptionsDto", b =>
                {
                    b.HasOne("QuizApi.Data.Models.Question", null)
                        .WithMany("options")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("QuizApi.Data.Models.Question", b =>
                {
                    b.Navigation("options");
                });
#pragma warning restore 612, 618
        }
    }
}
